parameters:
  os: linux
  workspace: .

jobs:
- job: ${{ format(parameters.os, parameters.name) }}

  pool:
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: ubuntu-20.04
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: macOS-10.14

  steps:
    - task: GoTool@0
      inputs: 
        version: 1.14

    - task: CmdLine@2
      inputs:
        script: |
          cd $ {{ parameters.workspace }}
          go test ./...


